name: CI

on:
  push:
    branches:
      - main
    paths-ignore: 
      - '.github/**'
      - 'docs/**'
      - '**/.gitignore'
      - 'build.sh'
      - 'clean.sh'
      - 'test.sh'
      - 'CONTRIBUTORS'
      - 'LICENSE'
      - 'README.MD'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/.gitignore'
      - 'build.sh'
      - 'clean.sh'
      - 'test.sh'
      - 'CONTRIBUTORS'
      - 'LICENSE'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: '18'
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 18
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Execute build
      run: chmod +x build.sh ./build.sh
    - name: Execute tests
      run: chmod +x test.sh ./test.sh
